from Segmentation_Params import Segmentation_Params

heart_params_seg = Segmentation_Params(delta = 8,
                                    GL_epsilon = 1e0,
                                    steps = 10,
                                    margin_proportion = 0.0225,
                                    maxiterations = 50,
                                    grad_Bhatt_MC = 10,
                                    Bhatt_MC = 50,
                                    sigma = 1e-2,
                                    beta = 2*1e2,
                                    gamma = 2*2*1e-2,
                                    momentum_u = 1e-5,
                                    threshold_seg = 0.25,
                                    max_sparsity_seg = 2000000,
                                    batch_size = 700,
                                    method = 'random',
                                    dirac = 0,
                                    verbose = True)

triangle_params_seg = Segmentation_Params(delta = 2,
                                    GL_epsilon = 1e0,
                                    steps = 100,
                                    margin_proportion = 0.05,
                                    maxiterations = 25,
                                    grad_Bhatt_MC = 10,
                                    Bhatt_MC = 50,
                                    sigma = 1e-2,
                                    beta = 2*1e2,
                                    gamma = 2*2*1e-2,
                                    momentum_u = 1e-5,
                                    threshold_seg = 0.01,
                                    max_sparsity_seg = 62500,
                                    batch_size = 700,
                                    method = 'random',
                                    dirac = 0,
                                    verbose = True)

rectangle_params_seg = Segmentation_Params(delta = 2,
                                    GL_epsilon = 1e0,
                                    steps = 100,
                                    margin_proportion = 0.05,
                                    maxiterations = 25,
                                    grad_Bhatt_MC = 10,
                                    Bhatt_MC = 50,
                                    sigma = 1e-2,
                                    beta = 2*1e2,
                                    gamma = 2*2*1e-2,
                                    momentum_u = 1e-5,
                                    threshold_seg = 0.01,
                                    max_sparsity_seg = 62500,
                                    batch_size = 700,
                                    method = 'random',
                                    dirac = 0,
                                    verbose = True)
